local plugins = {
  {"nvim-lua/plenary.nvim"},
  {"nvim-lua/popup.nvim"},
  require 'mynvim.plugins.cmp',
  require 'mynvim.plugins.telescope',
  require 'mynvim.plugins.nvim-tree',
  require 'mynvim.plugins.lsp-zero',
  require 'mynvim.plugins.nvim-treesitter',
  require 'mynvim.plugins.mini',
  require 'mynvim.plugins.copilot',
  require 'mynvim.plugins.theme',
  require 'mynvim.plugins.aerial',
  {"ludovicchabant/vim-gutentags"},
  {"tpope/vim-surround"},
  {"tpope/vim-fugitive"},
  {"tpope/vim-commentary"},
  {"sheerun/vim-polyglot"},
  {"junegunn/fzf"},
  {"junegunn/fzf.vim"},
  {"webdevel/tabulous"},
  -- {"preservim/tagbar"},
}
require("lazy").setup(plugins, opts)
